### ISSUE TITLE
macOS Build Failure

### ISSUE THREAD

**Issue by eleev** [sparrowcode/SwiftBoost#11]
Hi, 

## Issue Description
While trying to build the package for a macOS target, I encountered a build failure. The failure is caused by the recent integration of a new API that doesn't include the `#available` attribute to ensure backwards compatibility with earlier macOS versions.

## Steps to Reproduce
Clone the repository onto a macOS system running a version 13.0+.
Run swift build in the terminal or `Xcode`. The build fails for the macOS target.

## Expected Result
The project should build successfully, regardless of the macOS version.

## Actual Result
The build fails with an error message indicating that the new API is not available in the macOS version being used and suggesting that #available attribute is used to fix it. 

## Next Steps
I'm going to follow up with a pull request with a fix and a small refactoring. #12

**Comment by ivanvorobei** [comment]
Closed because resolved by PR.
